# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{roadtrip}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kenton Newby"]
  s.date = %q{2010-08-28}
  s.description = %q{This is a quick little gem that uses Google Maps to determine the distance, duration and fuel costs for driving between two user defined points. Just like Google Maps, the starting and destination points can be full addresses, city/state combinations, or just ZIP codes.}
  s.email = %q{kentonnewby@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".DS_Store",
     ".gitignore",
     "History.txt",
     "Manifest.txt",
     "PostInstall.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "features/create_trip.feature",
     "features/step_definitions/roadtrip_steps.rb",
     "lib/roadtrip.rb",
     "pkg/roadtrip-0.0.1.gem",
     "pkg/roadtrip-0.0.1.tgz",
     "pkg/roadtrip-0.0.1/History.txt",
     "pkg/roadtrip-0.0.1/Manifest.txt",
     "pkg/roadtrip-0.0.1/PostInstall.txt",
     "pkg/roadtrip-0.0.1/README.rdoc",
     "pkg/roadtrip-0.0.1/Rakefile",
     "pkg/roadtrip-0.0.1/lib/roadtrip.rb",
     "pkg/roadtrip-0.0.1/script/console",
     "pkg/roadtrip-0.0.1/script/destroy",
     "pkg/roadtrip-0.0.1/script/generate",
     "pkg/roadtrip-0.0.1/spec/roadtrip_spec.rb",
     "pkg/roadtrip-0.0.1/spec/spec.opts",
     "pkg/roadtrip-0.0.1/spec/spec_helper.rb",
     "pkg/roadtrip-0.0.1/tasks/rspec.rake",
     "pkg/roadtrip-0.0.2.gem",
     "pkg/roadtrip-0.0.2.tgz",
     "pkg/roadtrip-0.0.2/History.txt",
     "pkg/roadtrip-0.0.2/Manifest.txt",
     "pkg/roadtrip-0.0.2/PostInstall.txt",
     "pkg/roadtrip-0.0.2/README.rdoc",
     "pkg/roadtrip-0.0.2/Rakefile",
     "pkg/roadtrip-0.0.2/lib/roadtrip.rb",
     "pkg/roadtrip-0.0.2/script/console",
     "pkg/roadtrip-0.0.2/script/destroy",
     "pkg/roadtrip-0.0.2/script/generate",
     "pkg/roadtrip-0.0.2/spec/roadtrip_spec.rb",
     "pkg/roadtrip-0.0.2/spec/spec.opts",
     "pkg/roadtrip-0.0.2/spec/spec_helper.rb",
     "pkg/roadtrip-0.0.2/tasks/rspec.rake",
     "pkg/roadtrip-0.0.3.gem",
     "pkg/roadtrip-0.0.3.tgz",
     "pkg/roadtrip-0.0.3/History.txt",
     "pkg/roadtrip-0.0.3/Manifest.txt",
     "pkg/roadtrip-0.0.3/PostInstall.txt",
     "pkg/roadtrip-0.0.3/README.rdoc",
     "pkg/roadtrip-0.0.3/Rakefile",
     "pkg/roadtrip-0.0.3/lib/roadtrip.rb",
     "pkg/roadtrip-0.0.3/script/console",
     "pkg/roadtrip-0.0.3/script/destroy",
     "pkg/roadtrip-0.0.3/script/generate",
     "pkg/roadtrip-0.0.3/spec/roadtrip_spec.rb",
     "pkg/roadtrip-0.0.3/spec/spec.opts",
     "pkg/roadtrip-0.0.3/spec/spec_helper.rb",
     "pkg/roadtrip-0.0.3/tasks/rspec.rake",
     "pkg/roadtrip-0.1.0.gem",
     "roadtrip.gemspec",
     "script/console",
     "script/destroy",
     "script/generate",
     "spec/roadtrip_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tasks/rspec.rake"
  ]
  s.homepage = %q{http://github.com/kenton/roadtrip}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Use Google Maps to find the cost, duration and distance for road trips}
  s.test_files = [
    "spec/roadtrip_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

